apiVersion: v1
kind: Service
metadata:
  name: ejabberd-nodeports
spec:
  type: NodePort
  ports:
  - name: adminhttps
    nodePort: 30030
    port: 5443
    protocol: TCP
    targetPort: 5443
  - name: c2s
    nodePort: 30031
    port: 5222
    protocol: TCP
    targetPort: 5222
  selector:
    app: ejabberd
    statefulset.kubernetes.io/pod-name: ejabberd-0
