replicaCount: 3

adminPassword: admin
cookieName: ejabberdcookie

storage:
  className: null
  dataSize: 1Gi
  logSize: 500Mi
  uploadSize: 250Mi

image:
  repository: hv86/ejabberd-cluster:1.0.0
  tag: 1.0.0
  pullPolicy: IfNotPresent
  pullSecret: null

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}